Console.WriteLine(@"\                     /");
Console.WriteLine(@" \                   /");
Console.WriteLine(@"  \                 /");
Console.WriteLine(@"   \               /");
Console.WriteLine(@"    \             /");
Console.WriteLine(@"     \           /");
Console.WriteLine(@"      \         /");
Console.WriteLine(@"       \       /");
Console.WriteLine(@"        \ ____/");
Console.WriteLine(@"         :    :");
Console.WriteLine(@"         :    :");
Console.WriteLine(@"          /  \");